#!/usr/bin/env python3
"""Regenerate src/cli/IntOpcodes.inc from a fallout2-ce checkout.

The compiled Fallout 2 script (.int) opcode names are not shipped game data; the engine is the only
source of truth. This walks the same registrations the interpreter performs at startup:

  * interpreter.h            - core VM opcodes (OPCODE_* enum, 0x8000..0x804B)
  * interpreter_extra.cc     - game opcodes, named by the original op_* comment on each registration
  * interpreter_lib.cc       - window/sound/movie opcodes
  * sfall_opcodes.cc         - sfall extensions

A registration without an op_* comment keeps the engine's handler identifier. The dispatcher indexes
its table with (opcode & 0x3FF), so the table is keyed the same way; two registrations landing on one
index with different names are a hard error rather than a silent pick.

Usage: tools/gen_int_opcodes.py /path/to/fallout2-ce > src/cli/IntOpcodes.inc
"""
import re
import subprocess
import sys


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else '.'
    commit = subprocess.check_output(['git', '-C', root, 'log', '-1', '--format=%h'], text=True).strip()
    entries = {}

    def add(index, name, source):
        if index in entries and entries[index][0] != name:
            sys.exit(f'opcode index 0x{index:03X} registered as both {entries[index][0]} and {name}')
        entries.setdefault(index, (name, source))

    core = open(f'{root}/src/interpreter.h').read()
    for name, value in re.findall(r'(OPCODE_[A-Z_0-9]+)\s*=\s*(0x[0-9A-Fa-f]+)', core):
        if int(value, 16) & 0x8000:
            add(int(value, 16) & 0x3FF, name, 'interpreter.h')

    registration = re.compile(
        r'interpreterRegisterOpcode\((0x[0-9A-Fa-f]+),\s*([A-Za-z_0-9]+)\);[ \t]*(?://[ \t]*([a-z_0-9]+))?')
    for source in ('interpreter_extra.cc', 'interpreter_lib.cc', 'sfall_opcodes.cc'):
        for value, handler, comment in registration.findall(open(f'{root}/src/{source}').read()):
            add(int(value, 16) & 0x3FF, comment or handler, source)

    print('// Generated by tools/gen_int_opcodes.py from fallout2-ce ' + commit + ' - do not edit by hand.')
    print('// { index = opcode & 0x3FF, engine name }. See the script for the sources it walks.')
    for index, (name, _) in sorted(entries.items()):
        print(f'{{ 0x{index:03X}, "{name}" }},')


if __name__ == '__main__':
    main()
