#!/usr/bin/env python3
"""Regenerate src/cli/IntOpcodes.inc from a fallout2-ce checkout."""
#
# The compiled Fallout 2 script (.int) opcode names are not shipped game data; the engine is the only
# source of truth. This walks the same registrations the interpreter performs at startup:
#
#   * interpreter.h            - core VM opcodes (OPCODE_* enum, 0x8000..0x804B)
#   * interpreter_extra.cc     - game opcodes, named by the original op_* comment on each registration
#   * interpreter_lib.cc       - window/sound/movie opcodes
#   * sfall_opcodes.cc         - sfall extensions
#
# A registration without an op_* comment keeps the engine's handler identifier. The dispatcher indexes
# its table with (opcode & 0x3FF), so the table is keyed the same way; two registrations landing on one
# index with different names are a hard error rather than a silent pick.
#
# Run it from the root of the fallout2-ce checkout; it takes no arguments:
#   cd /path/to/fallout2-ce && python3 /path/to/gecko/tools/gen_int_opcodes.py > /path/to/gecko/src/cli/IntOpcodes.inc

import re
import sys
from pathlib import Path

# The only files read, relative to the checkout's src/ directory.
REGISTRATION_SOURCES = ('interpreter_extra.cc', 'interpreter_lib.cc', 'sfall_opcodes.cc')
CORE_OPCODES_SOURCE = 'interpreter.h'


def checkout_root():
    """Return the current directory, which must be the root of a fallout2-ce checkout."""
    root = Path.cwd()
    if not (root / 'src' / CORE_OPCODES_SOURCE).is_file():
        sys.exit(f'run this from the root of a fallout2-ce checkout ({root} has no src/{CORE_OPCODES_SOURCE})')
    return root


def read_source(root, name):
    """Read one of the known engine sources, which must resolve inside the checkout."""
    path = (root / 'src' / name).resolve(strict=True)
    if not path.is_relative_to(root.resolve()):
        sys.exit(f'src/{name} resolves outside {root}')
    return path.read_text(encoding='utf-8')


def head_commit(root):
    """Return the checkout's abbreviated HEAD commit, read from .git rather than by running git."""
    git_dir = root / '.git'
    if not git_dir.is_dir():
        return 'unknown'
    head = (git_dir / 'HEAD').read_text(encoding='utf-8').strip()
    if not head.startswith('ref: '):
        return head[:8]
    ref = head[len('ref: '):]
    ref_file = git_dir / ref
    if ref_file.is_file():
        return ref_file.read_text(encoding='utf-8').strip()[:8]
    packed = git_dir / 'packed-refs'
    if packed.is_file():
        for line in packed.read_text(encoding='utf-8').splitlines():
            parts = line.split()
            if len(parts) == 2 and parts[1] == ref:
                return parts[0][:8]
    return 'unknown'


def main():
    """Print the opcode table for the fallout2-ce checkout in the current directory."""
    if len(sys.argv) > 1:
        sys.exit('usage: run from the root of a fallout2-ce checkout, with no arguments')
    root = checkout_root()
    entries = {}

    def add(index, name, source):
        if index in entries and entries[index][0] != name:
            sys.exit(f'opcode index 0x{index:03X} registered as both {entries[index][0]} and {name}')
        entries.setdefault(index, (name, source))

    for name, value in re.findall(r'(OPCODE_\w+)\s*=\s*(0x[0-9A-Fa-f]+)', read_source(root, CORE_OPCODES_SOURCE)):
        if int(value, 16) & 0x8000:
            add(int(value, 16) & 0x3FF, name, CORE_OPCODES_SOURCE)

    registration = re.compile(r'interpreterRegisterOpcode\((0x[0-9A-Fa-f]+),\s*(\w+)\);[ \t]*(?://[ \t]*([a-z_0-9]+))?')
    for source in REGISTRATION_SOURCES:
        for value, handler, comment in registration.findall(read_source(root, source)):
            add(int(value, 16) & 0x3FF, comment or handler, source)

    print('// Generated by tools/gen_int_opcodes.py from fallout2-ce ' + head_commit(root) + ' - do not edit by hand.')
    print('// { index = opcode & 0x3FF, engine name }. See the script for the sources it walks.')
    for index, (name, _) in sorted(entries.items()):
        print(f'{{ 0x{index:03X}, "{name}" }},')


if __name__ == '__main__':
    main()
